### ISSUE TITLE
[Feature/Developer] POC | Check whether we can use Capacitor in our project

### ISSUE THREAD

**Issue by Kryschtzyk** [SEPBFWS121A/Planty#5]
**Is your feature request related to a problem? Please describe.**
The Frontend can only be accessed through a Website. It would be better if the application could be accessed as a smartphone app. 

**Describe the solution you'd like**
Create a proof of concept to see if the current web application is compatible with Electron. 
Estimate the effort required to move the application. 

Create proof of concept to see if the current web application is compatible with Capacitor.

**Comment by Mijusa** [comment]
Electron was not suitable because it only created an desktop app not mobile apps.

Switching to Capacitor which can create Apps for Android and IOS.

The POC contains everyting needed and the apps are already created.

To make sure the apps are running these steps are needed:
1 npm install @capacitor/cli@latest @capacitor/core@latest
2 npm run build
3 npx cap sync android
4 npx cap open android

For IOS change android to ios.
